server:
  port: 8080
spring:
  application:
    name: commandcenter
  profiles:
    active: dev
app:
  profile-picture:
    storage: local # or 's3'
    local-dir: uploads/profile-pictures/
    s3:
      bucket: your-bucket-name
      region: us-east-1
      base-url: https://your-bucket-name.s3.amazonaws.com/ 